package com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.3
 * 2012-01-18T16:21:52.994+01:00
 * Generated source version: 2.4.3
 */

@WebFault(name = "fault", targetNamespace = "http://midpoint.evolveum.com/xml/ns/public/common/fault-1.wsdl")
public class FaultMessage extends Exception {

    private com.evolveum.midpoint.xml.ns._public.common.fault_1.FaultType fault;

    public FaultMessage() {
        super();
    }

    public FaultMessage(String message) {
        super(message);
    }

    public FaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public FaultMessage(String message, com.evolveum.midpoint.xml.ns._public.common.fault_1.FaultType fault) {
        super(message);
        this.fault = fault;
    }

    public FaultMessage(String message, com.evolveum.midpoint.xml.ns._public.common.fault_1.FaultType fault,
            Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public com.evolveum.midpoint.xml.ns._public.common.fault_1.FaultType getFaultInfo() {
        return this.fault;
    }
}
