/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2012-01-18T16:21:53.018+01:00
 * Generated source version: 2.4.3
 */

@javax.jws.WebService(
        serviceName = "modelService",
        portName = "modelPort",
        targetNamespace = "http://midpoint.evolveum.com/xml/ns/public/model/model-1.wsdl",
        wsdlLocation = "file:/home/lazyman/Work/evolveum/midpoint/trunk/infra/schema/src/main/resources/xml/ns/private/model/modelWrapper.wsdl",
        endpointInterface = "com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl.ModelPortType")

public class ModelPortTypeImpl implements ModelPortType {

    private static final Logger LOG = Logger.getLogger(ModelPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl.ModelPortType#deleteObject(java.lang.String  objectType ,)java.lang.String  oid )*
     */
    public com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType deleteObject(
            java.lang.String objectType, java.lang.String oid) throws
            com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage {
        LOG.info("Executing operation deleteObject");
        System.out.println(objectType);
        System.out.println(oid);
        try {
            com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl.ModelPortType#listObjects(java.lang.String  objectType ,)com.evolveum.midpoint.xml.ns._public.common.common_1.PagingType  paging ,)com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectListType  objectList ,)com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType  result )*
     */
    public void listObjects(java.lang.String objectType,
            com.evolveum.midpoint.xml.ns._public.common.common_1.PagingType paging,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectListType> objectList,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType> result) throws
            com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage {
        LOG.info("Executing operation listObjects");
        System.out.println(objectType);
        System.out.println(paging);
        try {
            com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectListType objectListValue = null;
            objectList.value = objectListValue;
            com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType resultValue = null;
            result.value = resultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl.ModelPortType#listAccountShadowOwner(java.lang.String  accountOid ,)com.evolveum.midpoint.xml.ns._public.common.common_1.UserType  user ,)com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType  result )*
     */
    public void listAccountShadowOwner(java.lang.String accountOid,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.UserType> user,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType> result) throws
            com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage {
        LOG.info("Executing operation listAccountShadowOwner");
        System.out.println(accountOid);
        try {
            com.evolveum.midpoint.xml.ns._public.common.common_1.UserType userValue = null;
            user.value = userValue;
            com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType resultValue = null;
            result.value = resultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl.ModelPortType#addObject(com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectType  object ,)java.lang.String  oid ,)com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType  result )*
     */
    public void addObject(com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectType object,
            javax.xml.ws.Holder<java.lang.String> oid,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType> result) throws
            com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage {
        LOG.info("Executing operation addObject");
        System.out.println(object);
        try {
            java.lang.String oidValue = "";
            oid.value = oidValue;
            com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType resultValue = null;
            result.value = resultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl.ModelPortType#searchObjects(java.lang.String  objectType ,)com.evolveum.midpoint.xml.ns._public.common.common_1.QueryType  query ,)com.evolveum.midpoint.xml.ns._public.common.common_1.PagingType  paging ,)com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectListType  objectList ,)com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType  result )*
     */
    public void searchObjects(java.lang.String objectType,
            com.evolveum.midpoint.xml.ns._public.common.common_1.QueryType query,
            com.evolveum.midpoint.xml.ns._public.common.common_1.PagingType paging,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectListType> objectList,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType> result) throws
            com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage {
        LOG.info("Executing operation searchObjects");
        System.out.println(objectType);
        System.out.println(query);
        System.out.println(paging);
        try {
            com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectListType objectListValue = null;
            objectList.value = objectListValue;
            com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType resultValue = null;
            result.value = resultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl.ModelPortType#listResourceObjectShadows(java.lang.String  resourceOid ,)java.lang.String  resourceObjectShadowType ,)com.evolveum.midpoint.xml.ns._public.common.common_1.ResourceObjectShadowListType  resourceObjectShadowList ,)com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType  result )*
     */
    public void listResourceObjectShadows(java.lang.String resourceOid, java.lang.String resourceObjectShadowType,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.ResourceObjectShadowListType> resourceObjectShadowList,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType> result) throws
            com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage {
        LOG.info("Executing operation listResourceObjectShadows");
        System.out.println(resourceOid);
        System.out.println(resourceObjectShadowType);
        try {
            com.evolveum.midpoint.xml.ns._public.common.common_1.ResourceObjectShadowListType resourceObjectShadowListValue = null;
            resourceObjectShadowList.value = resourceObjectShadowListValue;
            com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType resultValue = null;
            result.value = resultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl.ModelPortType#getPropertyAvailableValues(java.lang.String  oid ,)com.evolveum.midpoint.xml.ns._public.common.common_1.PropertyReferenceListType  properties ,)com.evolveum.midpoint.xml.ns._public.common.common_1.PropertyAvailableValuesListType  propertyAvailableValuesList ,)com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType  result )*
     */
    public void getPropertyAvailableValues(java.lang.String oid,
            com.evolveum.midpoint.xml.ns._public.common.common_1.PropertyReferenceListType properties,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.PropertyAvailableValuesListType> propertyAvailableValuesList,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType> result) throws
            com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage {
        LOG.info("Executing operation getPropertyAvailableValues");
        System.out.println(oid);
        System.out.println(properties);
        try {
            com.evolveum.midpoint.xml.ns._public.common.common_1.PropertyAvailableValuesListType propertyAvailableValuesListValue = null;
            propertyAvailableValuesList.value = propertyAvailableValuesListValue;
            com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType resultValue = null;
            result.value = resultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl.ModelPortType#importFromResource(java.lang.String  resourceOid ,)javax.xml.namespace.QName  objectClass )*
     */
    public com.evolveum.midpoint.xml.ns._public.common.common_1.TaskType importFromResource(
            java.lang.String resourceOid, javax.xml.namespace.QName objectClass) throws
            com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage {
        LOG.info("Executing operation importFromResource");
        System.out.println(resourceOid);
        System.out.println(objectClass);
        try {
            com.evolveum.midpoint.xml.ns._public.common.common_1.TaskType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl.ModelPortType#listResourceObjects(java.lang.String  resourceOid ,)javax.xml.namespace.QName  objectType ,)com.evolveum.midpoint.xml.ns._public.common.common_1.PagingType  paging ,)com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectListType  objectList ,)com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType  result )*
     */
    public void listResourceObjects(java.lang.String resourceOid, javax.xml.namespace.QName objectType,
            com.evolveum.midpoint.xml.ns._public.common.common_1.PagingType paging,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectListType> objectList,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType> result) throws
            com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage {
        LOG.info("Executing operation listResourceObjects");
        System.out.println(resourceOid);
        System.out.println(objectType);
        System.out.println(paging);
        try {
            com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectListType objectListValue = null;
            objectList.value = objectListValue;
            com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType resultValue = null;
            result.value = resultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl.ModelPortType#getObject(java.lang.String  objectType ,)java.lang.String  oid ,)com.evolveum.midpoint.xml.ns._public.common.common_1.PropertyReferenceListType  resolve ,)com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectType  object ,)com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType  result )*
     */
    public void getObject(java.lang.String objectType, java.lang.String oid,
            com.evolveum.midpoint.xml.ns._public.common.common_1.PropertyReferenceListType resolve,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectType> object,
            javax.xml.ws.Holder<com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType> result) throws
            com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage {
        LOG.info("Executing operation getObject");
        System.out.println(objectType);
        System.out.println(oid);
        System.out.println(resolve);
        try {
            com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectType objectValue = null;
            object.value = objectValue;
            com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType resultValue = null;
            result.value = resultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl.ModelPortType#modifyObject(java.lang.String  objectType ,)com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectModificationType  objectChange )*
     */
    public com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType modifyObject(
            java.lang.String objectType,
            com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectModificationType objectChange) throws
            com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage {
        LOG.info("Executing operation modifyObject");
        System.out.println(objectType);
        System.out.println(objectChange);
        try {
            com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage("FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.evolveum.midpoint.xml.ns._public.model.model_1_wsdl.ModelPortType#testResource(java.lang.String  resourceOid )*
     */
    public com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType testResource(
            java.lang.String resourceOid) throws com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage {
        LOG.info("Executing operation testResource");
        System.out.println(resourceOid);
        try {
            com.evolveum.midpoint.xml.ns._public.common.common_1.OperationResultType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new com.evolveum.midpoint.xml.ns._public.common.fault_1_wsdl.FaultMessage("FaultMessage...");
    }

}
