/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.evolveum.midpoint.xml.ns._private.fake.fake_1_wsdl;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2012-01-18T16:21:54.457+01:00
 * Generated source version: 2.4.3
 */

@javax.jws.WebService(
        serviceName = "fakeService",
        portName = "fakePort",
        targetNamespace = "http://midpoint.evolveum.com/xml/ns/private/fake/fake-1.wsdl",
        wsdlLocation = "file:/home/lazyman/Work/evolveum/midpoint/trunk/infra/schema/src/main/resources/xml/ns/private/fake/fakeWrapper.wsdl",
        endpointInterface = "com.evolveum.midpoint.xml.ns._private.fake.fake_1_wsdl.FakePortType")

public class FakePortTypeImpl implements FakePortType {

    private static final Logger LOG = Logger.getLogger(FakePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.evolveum.midpoint.xml.ns._private.fake.fake_1_wsdl.FakePortType#fake(java.lang.String  fakePart )*
     */
    public void fake(javax.xml.ws.Holder<java.lang.String> fakePart) {
        LOG.info("Executing operation fake");
        System.out.println(fakePart.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
