package com.evolveum.midpoint.xml.ns._private.fake.fake_1_wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2012-01-18T16:21:54.468+01:00
 * Generated source version: 2.4.3
 */
@WebService(targetNamespace = "http://midpoint.evolveum.com/xml/ns/private/fake/fake-1.wsdl", name = "fakePortType")
@XmlSeeAlso({com.evolveum.midpoint.xml.ns._public.resource.capabilities_1.ObjectFactory.class, com.evolveum.midpoint.xml.ns._public.connector.icf_1.resource_schema_1.ObjectFactory.class, com.evolveum.midpoint.xml.ns._public.communication.workflow_1.ObjectFactory.class, com.evolveum.midpoint.xml.ns._public.common.common_1.ObjectFactory.class, com.evolveum.midpoint.xml.ns._public.connector.icf_1.connector_schema_1.ObjectFactory.class, org.w3._2001._04.xmlenc.ObjectFactory.class, com.evolveum.midpoint.xml.ns._public.resource.resource_schema_1.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class, com.evolveum.midpoint.xml.ns._public.common.annotation_1.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface FakePortType {

    @WebMethod
    public void fake(
            @WebParam(partName = "fakePart", mode = WebParam.Mode.INOUT, name = "fakePart")
            javax.xml.ws.Holder<java.lang.String> fakePart
    );
}
