package com.evolveum.midpoint.xml.ns._private.fake.fake_1_wsdl;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2012-01-18T16:21:54.474+01:00
 * Generated source version: 2.4.3
 */
@WebServiceClient(name = "fakeService",
        wsdlLocation = "file:/home/lazyman/Work/evolveum/midpoint/trunk/infra/schema/src/main/resources/xml/ns/private/fake/fakeWrapper.wsdl",
        targetNamespace = "http://midpoint.evolveum.com/xml/ns/private/fake/fake-1.wsdl")
public class FakeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://midpoint.evolveum.com/xml/ns/private/fake/fake-1.wsdl", "fakeService");
    public final static QName FakePort = new QName("http://midpoint.evolveum.com/xml/ns/private/fake/fake-1.wsdl", "fakePort");

    static {
        URL url = null;
        try {
            url = new URL("file:/home/lazyman/Work/evolveum/midpoint/trunk/infra/schema/src/main/resources/xml/ns/private/fake/fakeWrapper.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FakeService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "file:/home/lazyman/Work/evolveum/midpoint/trunk/infra/schema/src/main/resources/xml/ns/private/fake/fakeWrapper.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FakeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FakeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FakeService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     * @return returns FakePortType
     */
    @WebEndpoint(name = "fakePort")
    public FakePortType getFakePort() {
        return super.getPort(FakePort, FakePortType.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns FakePortType
     */
    @WebEndpoint(name = "fakePort")
    public FakePortType getFakePort(WebServiceFeature... features) {
        return super.getPort(FakePort, FakePortType.class, features);
    }

}
